// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtkoulzbrvzuobddmizk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0a291bHpicnZ6dW9iZGRtaXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzEyNzcsImV4cCI6MjA2NDgwNzI3N30.pHq1eArckpCeFrOUZUwPdGempL8FGo0jbmKH8cifAHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);